export const DataPercobaan = [
  {
    title: 'Ujian CPNS',
    time: 'Durasi 01:45:00',
    soal: '100',
    tag: ['Free', 'Sudah Dikerjakan'],
    skor: '381',
    maxSkor: '550',
    nilai: [
      {
        title: 'TWK',
        nilai: 75,
        true: 15,
        total: 30,
      },
      {
        title: 'TIU',
        nilai: 75,
        true: 15,
        total: 35,
      },
      {
        title: 'TKP',
        nilai: 191,
        true: 45,
        total: 45,
      },
    ],
    skorRataRata: 350,
    peringkat: 64,
    totalPeserta: 3543,
    waktu: '01:45:00',
  },
  {
    title: 'Sub Ujian MATEMATIKA 2, Bahasa Inggris, IPA, IPS, BAHASA INDONESIA',
    time: 'Durasi 01:45:00',
    soal: '100',
    tag: ['Premium', 'Belum Dikerjakan'],
    skor: null,
    maxSkor: null,
    nilai: [],
    skorRataRata: null,
    peringkat: null,
    totalPeserta: 3543,
    waktu: '01:45:00',
  },
  {
    title: 'Tes TIU CPNS',
    time: 'Durasi 01:45:00',
    soal: '100',
    tag: ['Premium', 'Belum Dikerjakan'],
    skor: null,
    maxSkor: null,
    nilai: [],
    skorRataRata: null,
    peringkat: null,
    totalPeserta: 3543,
    waktu: '01:45:00',
  },
]
