export const DataLesson = [
  {
    title: 'Bimbel SKD Kedinasan',
    tag: ['Kedinasan'],
    lessons: '18 Lessons',
    time: '2h 40min',
    imgBg: '/img/app-bg.jpg',
    imgProfile: '/img/logo.png',
    type: ['completed'],
  },
  {
    title: 'Bimbel SKD CPNS/PPPK',
    tag: ['CPNS', 'PPPK'],
    lessons: '18 Lessons',
    time: '2h 40min',
    imgBg: '/img/app-bg.jpg',
    imgProfile: '/img/logo.png',
    type: [''],
  },
  {
    title: 'Bimbel TKD BUMN',
    tag: ['BUMN'],
    lessons: '18 Lessons',
    time: '2h 40min',
    imgBg: '/img/app-bg.jpg',
    imgProfile: '/img/logo.png',
    type: ['favorite'],
  },
  {
    title: 'Bimbel Bahasa Inggris TOEFL, CPNS/PPPK, BUMN & Kedinasan',
    tag: ['CPNS', 'PPPK', 'BUMN', 'Kedinasan'],
    lessons: '18 Lessons',
    time: '2h 40min',
    imgBg: '/img/app-bg.jpg',
    imgProfile: '/img/logo.png',
    type: ['completed'],
  },
  {
    title: 'Bimbel AKHLAK BUMN',
    tag: ['BUMN'],
    lessons: '18 Lessons',
    time: '2h 40min',
    imgBg: '/img/app-bg.jpg',
    imgProfile: '/img/logo.png',
    type: ['ongoing', 'favorite'],
  },
]
